pilot/pilot/urls.py
#from django.conf.urls.defaults import patterns, include, url
from django.conf.urls import include, url, patterns
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.contrib.auth import views
from mentee.views import mentee_home, mentee_list, mentee_detail, mentee_create, mentee_update
from login.views import login_user, logout_user, register_user, Mentor_List, passwordreset, password_change_done, Mentor_Table, mentor_detail
from log.views import logtable, Log_Create_Form, log_details

urlpatterns = [
    #url(r'^user/(?P<user_id>\d+)/user_edit/password/$', auth_views.password_change),
    #url('^', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^password_change/$', passwordreset, name='passwordreset'),
    url(r'^password_change/done/$', password_change_done, name='password_change_done'),
    url(r'^register/', register_user, name='register'),
    url(r'^login/', login_user, name='login'),
    url(r'^logout/', logout_user, name='logout'),
    url(r'^ov/$', Mentor_List, name='outreachvolunteer'),
    url(r'^ov/table$', Mentor_Table, name='outreachvolunteertable'),
    url(r'^ov/(?P<id>\d+)/$', mentor_detail, name="mentor_detail"),
    url(r'^mentee/$', mentee_list, name='mentees'),
    url(r'^mentee/(?P<id>\d+)/$', mentee_detail, name="mentee_detail"),
    url(r'^activities/(?P<id>\d+)/$', log_details, name="logdetails"),
    url(r'^mentee/create/$', mentee_create, name='mentee_create'),
    url(r'^mentee/(?P<id>\d+)/edit/$', mentee_update, name="mentee_update"),
    url(r'^activities/$', logtable, name="activities"),
    url(r'^activities/new$', Log_Create_Form, name="newactivity"),   

    url(r'^$', mentee_home, name='home'),
]

pilot/mentee/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from config.models import Chapter, Region, UserProfile

class Mentee(models.Model):
    MALE = 'Male'
    FEMALE = 'Female'
    HOMEPHONE = 'Home Phone'
    BUSINESSPHONE = 'Business Phone'
    MOBILEPHONE = 'Mobile Phone'
    PHONE = [
        (HOMEPHONE, 'Home Phone'),
        (BUSINESSPHONE, 'Business Phone'),
        (MOBILEPHONE, 'Mobile Phone'),
    ]
    SEX = [
        (MALE, 'Male'),
        (FEMALE, 'Female',)
    ]
    CRM_Record_ID = models.CharField(max_length=80, blank=True)
    CRM_Outreach_Request_ID = models.CharField(max_length=80, blank=True)
    First_Name = models.CharField(max_length=80)
    Last_Name = models.CharField(max_length=80, blank=True)
    Gender = models.CharField(max_length=80, choices=SEX, blank=True)
    Mailing_Address_Line_1 = models.CharField(max_length=80, blank=True)
    Mailing_Address_Line_2 = models.CharField(max_length=80, blank=True)
    Mailing_Address_Line_3 = models.CharField(max_length=80, blank=True)
    City = models.CharField(max_length=80, blank=True)
    State = models.CharField(max_length=80, blank=True)
    Zip = models.CharField(max_length=80, blank=True)
    Preferred_Phone = models.CharField(max_length=80, choices=PHONE, blank=True)
    Home_Number = models.CharField(max_length=15, blank=True)
    Business_Number = models.CharField(max_length=25, blank=True)
    Mobile_Phone = models.CharField(max_length=15, blank=True)
    Email = models.EmailField(blank=True)
    Employer = models.CharField(max_length=80, blank=True)
    Has_Diabetes = models.BooleanField(default=False)
    Child_T1D_name = models.CharField(max_length=80, blank=True)
    Child_Gender = models.CharField(max_length=80, choices=SEX, blank=True)
    Childs_DOB = models.DateField(auto_now=False, auto_now_add=False, blank=True)
    Diagnosis_Date =  models.DateField(auto_now=False, auto_now_add=False, blank=True)
    Hospital = models.CharField(max_length=80, blank=True)
    Endo = models.CharField(max_length=80, blank=True)
    School = models.CharField(max_length=80, blank=True)
    Grade = models.CharField(max_length=80, blank=True)
    Chapter = models.ForeignKey(Chapter)
    Region = models.ForeignKey(Region)
    Mentor_Assigned = models.ForeignKey(UserProfile)
    Notes = models.TextField(blank=True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    Created_By = models.CharField(max_length=80, blank=True)
    Updated_By = models.CharField(max_length=80, blank=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __unicode__(self):
        return self.First_Name + ' ' + self.Last_Name

    def get_absolute_url(self):
        return reverse('mentee_detail', kwargs={"id": self.id})

pilot/log/forms.py
from django import forms
from django.forms.widgets import Select
from config.models import UserProfile, Chapter
from config import models
from mentee.models import Mentee
from .models import log

class LogForm(forms.ModelForm):
    # def __init__(self, user=None, **kwargs):
    #super(LogForm, self).__init__(**kwargs)
    # res_user =  UserProfile.objects.get(User=user).User
    # res_chapter =  str(UserProfile.objects.get(User=user).Chapter)
    # res_region =  UserProfile.objects.get(User=user).Region
    # res_perm =  UserProfile.objects.get(User=user).Mentor_Type


    #Activity_Date = forms.DateField(widget=forms.SelectDateWidget(empty_label="Nothing"))

    class Meta:
        model = log
        exclude = [
            "timestamp",
            "Log_Region",
            "Log_Chapter",
            #"Log_User",
        ]
        widgets = {
            'Log_Chapter': Select(),
        }

pilot/mentee/forms.py
from django import forms
from .models import Mentee
from django.contrib.admin import widgets

class MenteeForm(forms.ModelForm):
    #Diagnosis_Date = forms.DateField(widget=forms.SelectDateWidget(empty_label="Nothing"))
    class Meta:
        model = Mentee
        exclude = [
            "Created_By",
            "timestamp",
            "updated",
            "Updated_By",
        ]

pilot/log/views.py
from datetime import datetime
import json
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Count, Min, Sum, Avg
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import FormMixin, CreateView
from django.views.generic.list import ListView
from django import views
from config.models import Chapter, Region, UserProfile
from log.models import log
from .models import Mentee
from .forms import LogForm

@login_required
def logtable(request):
    if request.user.is_authenticated():
        user = request.user
        res_user =  request.session.get('User', default=None)
        res_chapter =  request.session.get('Chapter', default=None)
        res_region =  request.session.get('Region', default=None)
        res_perm =  request.session.get('Perm', default=None)
        mentor = UserProfile.objects.filter(User=user)
        if str(res_perm) == "Volunteer":
            instance_log = log.objects.filter(Log_User=mentor).order_by('-timestamp')
            context = {
                "instance_log": instance_log,
                "title": "My Activities",

            }
            return render(request, "log_table.html",context)

        elif str(res_perm) == "Chapter Staff":
            instance_log = log.objects.filter(Log_Chapter=res_chapter).order_by('-timestamp')
            context = {
                "instance_log": instance_log,
                "title": "My Chapters Activities"
            }
            return render(request, "log_table.html",context)

        elif str(res_perm) == "Regional Staff":
            instance_log = log.objects.filter(Log_Region=res_region).order_by('-timestamp')
            context = {
                "instance_log": instance_log,
                "title": "My Regions Activities"
            }
            return render(request, "log_table.html",context)

        elif str(res_perm) == "National Staff":
            instance_log = log.objects.all.order_by('-timestamp')
            context = {
                "instance_log": instance_log,
                "title": "All Activities"
            }
            return render(request, "log_table.html",context)

        else:
            messages.success(request, "You aren't authorized to view this record. If you feel this is in error please contact your chapter staff.")
            return render(request, "base.html")
    else:
        messages.success(request, "Please log in to view that page")
        return render(request, "base.html")

@login_required
def Log_Create_Form(request):
    user = request.user
    res_user =  request.session.get('User')
    res_chapter =  request.session.get('Chapter')
    res_region =  request.session.get('Region')
    res_perm =  request.session.get('Perm')
    form = LogForm(request.POST)
    mentor = UserProfile.objects.filter(User=user)
    #currentuser = UserProfile.objects.filter(User=user).values
    #form = LogForm(request.POST, instance=request.user)
    if str(res_perm) == "Volunteer":
        form.fields['Outreach_Family'].queryset = Mentee.objects.filter(Mentor_Assigned=mentor)
        form.fields['Log_User'].queryset = UserProfile.objects.filter(User=user)
    if str(res_perm) == "Chapter Staff":
        form.fields['Outreach_Family'].queryset = Mentee.objects.filter(Chapter=res_chapter)
        form.fields['Log_User'].queryset = UserProfile.objects.filter(User=user)
    if str(res_perm) == "Regional Staff":
        form.fields['Outreach_Family'].queryset = Mentee.objects.filter(Region=res_region)
        form.fields['Log_User'].queryset = UserProfile.objects.filter(User=user)

    context = {
        "form": form,
    }
    if request.POST:
        if form.is_valid():
            instance = form.save(commit=False)
            #instance.Log_User = request.User
            instance.timestamp = datetime.now()
            instance.Log_Chapter = res_chapter
            instance.Log_Region = res_region
            #instance.Log_User = currentuser
            instance.save()
            messages.success(request or None, "Saved")
            #return render(request, "Log_Form.html", context)
            return HttpResponseRedirect('/activities/', instance.id)

    else:
        messages.success(request or None, "Not Saved")
        return render(request, "Log_Form.html", context)

@login_required
def log_details(request, id=None):
    res_user =  request.session.get('User', default=None)
    res_chapter =  request.session.get('Chapter', default=None)
    res_region =  request.session.get('Region', default=None)
    res_perm =  request.session.get('Perm', default=None)
    if request.user.is_authenticated():
        instance = get_object_or_404(log, id=id)
        context = {
            "title": instance.Outreach_Family,
            "instance": instance,
        }
        return render(request, "Log_Detail.html", context)
    # if str(res_perm) == "Volunteer":
        # form.fields['Outreach_Family'].queryset = Mentee.objects.filter(Mentor_Assigned=res_user)
    # if str(res_perm) == "Chapter Staff":
        # form.fields['Outreach_Family'].queryset = Mentee.objects.filter(Chapter=res_chapter)
    # if str(res_perm) == "Regional Staff":
        # form.fields['Outreach_Family'].queryset = Mentee.objects.filter(Region=res_region)


    # else:
        # messages.success(request or None, "Not Saved")
        # return render(request, "Log_Form.html", context)

pilot/templates/Log_Form.html
{% extends "base.html" %}


{% block headtitle %}{{title}} | {{ block.super }}{% endblock headtitle %}
{% block title %}
    <div id="group-dir-search" class="dir-search" role="search">
        <h1 class="page-title">
            {{title}}
        </h1>
    </div><!-- #group-dir-search -->
{% endblock title %}
{% block header %}
<style>
  .form-control{
    width:100%;
  }
</style>
<script>
$(function() {
  $( "#id_Activity_Date" ).datepicker();
});
$(function() {
  $( "#id_Diagnosis_Date" ).datepicker();
});
</script>
{% endblock header %}

{% block content %}
        <H1>{{title}}</H1>
        <form method='POST' action=''>{% csrf_token %}
          {% load bootstrap %}
          {{ form.Activity_Date|bootstrap }}
          {{ form.Outreach_Family|bootstrap }}
          {{ form.Log_Method|bootstrap }}
          {{ form.JDRF_Resource_Sent|bootstrap }}
          {{ form.Log_Notes|bootstrap }}
          {{ form.Log_User|bootstrap }}
          <input type='submit' value='Create Activity' />
        </form>

{% endblock content %}

pilot/templates/base.html
<html>
    <head>
        <link rel='stylesheet' id='dashicons-css'  href='http://typeonenation.org/wp-includes/css/dashicons.min.css?ver=4.2.4' type='text/css' media='all' />
        <link rel='stylesheet' id='badges-css-css'  href='http://typeonenation.org/wp-content/plugins/t1n-badges/assets/css/badges.css?ver=0.4.2' type='text/css' media='all' />
        <link rel='stylesheet' id='buddyboss-wp-frontend-css'  href='http://typeonenation.org/wp-content/themes/t1n-parent/css/wordpress.css?ver=4.2.4' type='text/css' media='all' />
        <link rel='stylesheet' id='buddyboss-bp-frontend-css'  href='http://typeonenation.org/wp-content/themes/t1n-parent/css/buddypress.css?ver=4.2.4' type='text/css' media='all' />
        <link rel="stylesheet" type="text/css" href="http://typeonenation.org/wp-content/themes/typeonenation/assets/css/typeonenation.css">

        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.10.2.js"></script>
        <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    {% block extrastyle %}
    {% endblock%}
        <title>{% block headtitle %}Outrach Pilot{% endblock headtitle %}</title>
    </head>
    <body>
        <header class="header clearfix" role="banner">
            <div class="inset"><!--login-->
                {% if not user.is_authenticated %}
                <menu class="button-menu only--large -menu -loggedout">
                    <li class="-login" id="login" data-section="login" data-expanded="true">
                        <form action="{% url 'login' %}" method="post">{% csrf_token %}
                            {% if next %}
                            <input type="hidden" name="next" value="{{ next }}" />
                            {% endif %}
                            <p class="-field form-field form-field--text">
                                <!--<label for="username" aria-hidden="false">Username</label> -->
                                <input type="text" name="username" value="{{ username}}" placeholder="Username"/>
                                <!--<input id="username" name="log" type="text" autocomplete="off" aria-label="Username">-->
                            </p>
                            <p class="-field form-field form-field--text">
                                <!--<label for="password" aria-hidden="false">Password</label>-->
                                <input type="password" name="password" value=""placeholder="Password"/>
                                <!--<input id="password" name="pwd" type="password" autocomplete="off" aria-label="Password">-->
                            </p>
                            <p class="-field">
                                <!-- this is from django <input type="submit" value="Log In" />-->
                                <button class="btn" type="submit">Login</button>
                            </p>
                        </form>
                    </li>
                    <li data-section="login" data-expanded="false">
                        <button class="btn" aria-controls="login" aria-expanded="false" data-controls="login">Login</button>
                    </li>
                    <!--<li data-expanded="true">
                        <a class="btn btn--primary register-btn" href="#">Register</a>
                    </li>-->
                </menu>
                {% endif %}
                {% if user.is_authenticated %}
                <menu class="button-menu only--large -menu ">
                    <li>
                        <button class="btn" data-controls="login">Welcome back - {{user}}</button>
                    </li>
                    <li data-expanded="true">
                        <a class="btn btn--primary register-btn" href="{% url 'logout' %}">Log out</a>
                    </li>
                    <li></li>
                    <li data-expanded="true">
                        <a class="btn btn--primary register-btn" href="{% url 'passwordreset' %}">Change Password</a>
                    </li>
                </menu>
                {% endif %}
            </div>
            <!--Menu-->

        </header>
        <nav class="navigation">
            <ul id="menu-new-main-menu" class="inset">
                {% if not user.is_authenticated %}<li id="menu-item-118591" class="only--large -home menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-19 current_page_item menu-item-118591"><a href="{% url 'home' %}" aria-current="true">Home</a></li>{% endif %}
                {% if user.is_authenticated %}<li id="menu-item-118593" class="only--large -home menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-19 current_page_item menu-item-118591"><a href="{% url 'mentees' %}">Families</a></li>{% endif %}
                {% if request.user.is_staff %}<li id="menu-item-118594" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-118594"><a href="{% url 'outreachvolunteer' %}">Outreach Volunteers</a></li>{% endif %}
                {% if request.user.is_authenticated %}<li id="menu-item-118594" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-118594"><a href="{% url 'activities' %}">Activities</a></li>{% endif %}-->
                {% if request.user.is_staff %}<li id="menu-item-118594" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-118594"><a href="{% url 'mentee_create' %}">New Family</a></li>{% endif %}
                {% if request.user.is_authenticated %}<li id="menu-item-118594" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-118594"><a href="{% url 'newactivity' %}">New Activity</a></li>{% endif %}-->
                <!--<li id="menu-item-118607" class="t1n-resource menu-item menu-item-type-post_type menu-item-object-page menu-item-118607"><a href="http://typeonenation.org/resources/">Resources</a></li>
                <li id="menu-item-118598" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-118598"><a title="TypeOneNation Events" href="/events/">Events</a></li>
                <li id="menu-item-118599" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-118599"><a href="http://typeonenation.org/about-us/">About</a></li>-->
            </ul>
        </nav>
    <body>
        <div id="main-wrap">
            <div id="inner-wrap">
                <div id="page" class="hfeed site">
                    <div id="main" class="wrapper">
                        <div class="page-full-width">
                            <main class="main" {% block mainpadding %}style="padding-top:0px;"{% endblock mainpadding %} >
                                <div class="board inset inset--main">
                                    <div class="panel thread">
                                        {% block header %}
                                        <header id="groups-header" class="groups-banner page-header clearfix">
                                            {% block title %}
                                            <div id="group-dir-search" class="dir-search" role="search">
                                            {% block message %}
                                                {% if messages %}
                                                <div class="warning">
                                                <ul class="messages">
                                                    {% for message in messages %}
                                                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                                    {% endfor %}
                                                </ul>
                                                </div>
                                                {% endif %}
                                            {% endblock message %}
                                                <h1 class="page-title">
                                                    Outreach Pilot
                                                </h1>
                                            </div><!-- #group-dir-search -->
                                            <div class="group-parent">
                                                <p>
                                                    JDRF’s Outreach Program is the primary entry point into the organization, presenting programs and opportunities to the T1D community who will join us in our work to accelerate life-changing breakthroughs to cure, prevent and treat T1D and its complications.  With the help of trained and experienced volunteers, JDRF staff seeks to meet individuals with T1D and their families in their time of need order to build lasting relationships which will ultimately lead to their loyalty to JDRF’s mission. JDRF Outreach strategies have been evaluated and opportunities for growth were identified to better support chapters and branches in implementing an effective Outreach Program.  The JDRF Mentor Program is recognized as an area with great opportunity to strengthen the approach to nurture relationships with those new to JDRF.
                                                </p>
                                            </div>
                                            {% endblock title %}
                                        </header>
                                        {% endblock header %}
                                        <div class="clearfix"></div>
                                        <div class="entry-content">
                                            <div id="buddypress">

                                            {% block content %}
                                                <H1>Please log in!</H1>

                                            {% endblock content %}
                                            </div><!-- #buddypress -->
                                        </div><!-- .entry-content -->
                                    </div>
                                </div>
                            </main>
                        </div>
                    </div>
                </div>
                <footer id="colophon" role="contentinfo" style="transform: translateZ(0px);">
                    <div class="footer-inner-top">
                        <div class="footer-inner-bottom">
                            <div class="footer-inner">
                                <div id="footer-links">
                                    <div class="footer-social">

                                    </div>
                                </div>

                                <div id="footer-credits" class="last">
                                    <p>Copyright 2016 <a href="http://www.jdrf.org/" target="_blank" title="JDRF">JDRF</a></span></p>
                                </div>
                            </div><!-- .footer-inner -->
                        </div><!-- .footer-inner-bottom -->
                    </div>
                </footer>
            </div>
        </div>
<!--        <link rel='stylesheet' id='wangguard-bp-css'  href='http://typeonenation.org/wp-content/plugins/wangguard/css/wangguard-bp.css?ver=1.6' type='text/css' media='all' />
        <script type='text/javascript' src='http://typeonenation.org/wp-includes/js/admin-bar.min.js?ver=4.2.4'></script>
        <script type='text/javascript' src='http://typeonenation.org/wp-content/plugins/bbpress/templates/default/js/editor.js?ver=2.6-alpha-5215'></script>
        <script type='text/javascript' src='http://typeonenation.org/wp-content/plugins/member-posts/js/member-posts.js?ver=1.0'></script>
        <script type='text/javascript' src='http://typeonenation.org/wp-content/themes/t1n-parent/js/navigation.js?ver=1.0'></script>
        <script type='text/javascript' src='http://typeonenation.org/wp-content/themes/t1n-parent/js/jquery.touchSwipe.min.js?ver=1.0'></script>
        <script type='text/javascript' src='http://typeonenation.org/wp-content/themes/t1n-parent/js/idangerous.swiper.js?ver=1.9.2'></script>
        <script type='text/javascript' src='http://typeonenation.org/wp-content/themes/t1n-parent/js/jquery.fitvids.js?ver=1.0'></script>
        <script type='text/javascript' src='http://typeonenation.org/wp-content/themes/t1n-parent/js/mobile-main.js?ver=3.0'></script>
    -->
    </body>
</html>

pilot/templates/mentee_detail.html
{% extends "base.html" %}
{% block headtitle %}{{title}} | {{ block.super }}{% endblock headtitle %}
{% block mainpadding %} {% endblock mainpadding %}
{% block header %}
<header class="page-header">
    <h1><a href="{{ obj.get_absolute_url }}">{{ instance.First_Name }} {{ instance.Last_Name }}</a></h1>
    <div class="pag-count" id="group-dir-count-top">
        Created: {{instance.timestamp }} - Updated: {{ instance.updated }} by: {{instance.Updated_By}}
    </div>
    <h2>Outreach Volunteer: {{ instance.Mentor_Assigned }}</h2>
    <div class="fivecol left">
    <p>
        E-mail: {{ instance.Email }}<br />
        Preferred Phone: {{ instance.Preferred_Phone }}<br />
        Home Phone: {{ instance.Home_Number }}<br />
        Mobile Phone: {{ instance.Mobile_Phone }}<br />
        Business Phone: {{ instance.Business_Number }}<br />
        Address: {{ instance.Mailing_Address_Line_1 }}<br />
        Address 2: {{ instance.Mailing_Address_Line_2 }}<br />
        Address 3: {{ instance.Mailing_Address_Line_3 }}<br />
        City, State, Zip: {{ instance.City }}, {{ instance.State }} {{ instance.Zip }}<br />
        Employer: {{instance.Employer }}<br />
    </p>
    </div>
    <div class="fivecol right">
    <p>
        Chapter: {{ instance.Chapter }}<br />
        Region: {{ instance.Region }}<br />
        CRM Record ID: {{ instance.CRM_Record_ID }}<br />
        CRM Outreach ID: {{ instance.CRM_Outreach_Request_ID }}<br />
        Child with T1D: {{  instance.Child_T1D_name }}<br />
        Gender: {{ instance.Child_Gender }}<br />
        Child DOB: {{ instance.Childs_DOB }}<br />
        Diagnosis Date: {{ instance.Diagnosis_Date }}<br />
        Diagnosed at: {{ instance.Hospital }}/{{ instance.Endo }}<br />
        School/Grade: {{ instance.School }}/{{ instance.Grade }}
    </p>
    </div>
    <div class="tencol">
    <p>
       <strong> Notes:<br /> </strong>
        {{ instance.Notes }}
    </p>
    <p>
        <a href="edit/" class="button">Edit</a>
    </p>

	<!--<p class="cta">test</p>-->
    </div>
</header>
{% endblock header %}

{% block title %}

{% endblock title %}
{% block content %}
    <H1>{{title}}</H1>
    <div id="groups-dir-list" class="groups dir-list" style="width:100%">
        <!--<form method='GET' action=''>
            <input type='text' name='q' placeholder='Search Activities' />
            <input type='submit' value='search' />
        </form>-->
        <div id="pag-top" class="pagination">
            <div class="pag-count" id="group-dir-count-top"></div>
            <div class="pagination-links" id="group-dir-pag-top"></div>
        </div>
        <ul id="groups-list" class="item-list" >
            {% for obj in instance_log %}
            <li>
                <div class="item">
                    <a href="/activities/{{obj.id}}">
                    <div class="item-title">{{ obj.Log_Method }} on {{ obj.Activity_Date }} by {{ obj.Log_User }}</div>
                    </a>
                    <div class="item-meta"><span class="activity">{{ obj.Log_Chapter }}</span></div>
                    <div class="item-desc">Notes: {{ obj.Log_Notes }}</div>
                </div>
                <div class="action">
                    <div class="meta">
                        {{ obj.Log_User }} / {{ obj.Activity_Date }}
                    </div>
                </div>
                <div class="clear"></div>
            </li>
            {% endfor %}
        </ul>
        <div id="pag-bottom" class="pagination">
           <!-- <div class="pag-count" id="group-dir-count-bottom"></div>
            <div class="pagination-links" id="group-dir-pag-bottom">
                <span class='page-numbers current'>1</span>
            </div>-->
        </div>
    </div><!-- #groups-dir-list -->
{% endblock content %}

pilot/templates/mentee_form.html
{% extends "base.html" %}
{% block extrastyle %} | {{ block.super }}
{% endblock extrastyle %}
{% block headtitle %}{{title}} | {{ block.super }}{% endblock headtitle %}
{% block mainpadding %} {% endblock mainpadding %}
{% block message %}{% endblock message %}
{% block header %}
<style>
  .form-control{
    width:100%;
  }
</style>
<script>
$(function() {
  $( "#id_Childs_DOB" ).datepicker();
});
$(function() {
  $( "#id_Diagnosis_Date" ).datepicker();
});
</script>

<header class="page-header">
    <H1>{{title}}</H1>
    <div class="formfill">
    <form method="post" action=''>{% csrf_token %}
      {% load bootstrap %}
      {{ form.CRM_Record_ID|bootstrap }}
      {{ form.CRM_Outreach_Request_ID|bootstrap }}
      {{ form.First_Name|bootstrap }}
      {{ form.Last_Name|bootstrap }}
      {{ form.Gender|bootstrap }}
      {{ form.Mailing_Address_Line_1|bootstrap }}
      {{ form.Mailing_Address_Line_2|bootstrap }}
      {{ form.Mailing_Address_Line_3|bootstrap }}
      {{ form.City|bootstrap }}
      {{ form.State|bootstrap }}
      {{ form.Zip|bootstrap }}
      {{ form.Preferred_Phone|bootstrap }}
      {{ form.Home_Number|bootstrap }}
      {{ form.Business_Number|bootstrap }}
      {{ form.Mobile_Phone|bootstrap }}
      {{ form.Email|bootstrap }}
      {{ form.Employer|bootstrap }}
      {{ form.Has_Diabetes|bootstrap }}
      {{ form.Child_T1D_name|bootstrap }}
      {{ form.Childs_DOB|bootstrap }}
      {{ form.Diagnosis_Date|bootstrap }}
      {{ form.Hospital|bootstrap }}
      {{ form.Endo|bootstrap }}
      {{ form.School|bootstrap }}
      {{ form.Grade|bootstrap }}
      {{ form.Chapter|bootstrap }}
      {{ form.Region|bootstrap }}
      {{ form.Mentor_Assigned|bootstrap }}
      {{ form.Notes|bootstrap }}
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
</header>
{% endblock header %}

{% block title %}

{% endblock title %}
{% block content %}
{% endblock content %}